[window.padding]
x = 3
y = 3

[font]
size = 11.0

[font.normal]
family = "RobotoMono Nerd Font"

[colors.primary]
background = "#282C34"
foreground = "#ABB2BF"

[colors.normal]
black = "#5C6370"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#C678DD"
red = "#E06C75"
white = "#ABB2BF"
yellow = "#D19A66"
