[window.padding]
x = 3
y = 3

[font]
size = 11.0

[font.normal]
family = "RobotoMono Nerd Font"

[colors.primary]
background = "#F5EEE6"
foreground = "#222222"

[colors.normal]
black   = "#222222"
red     = "#B31D28"
green   = "#22863A"
yellow  = "#FED442"
blue    = "#005CC5"
magenta = "#D73A49"
cyan    = "#00BEFF"
white   = "#F5EEE6"
