[colors.bright]
black = "#5C6370"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#C678DD"
red = "#E06C75"
white = "#ABB2BF"
yellow = "#D19A66"

[colors.normal]
black = "#1E2127"
blue = "#61AFEF"
cyan = "#56B6C2"
green = "#98C379"
magenta = "#C678DD"
red = "#E06C75"
white = "#ABB2BF"
yellow = "#D19A66"

[colors.primary]
background = "#262626"
foreground = "#ABB2BF"

[cursor.style]
shape = "Underline"

[font.normal]
family = "RobotoMono Nerd Font"

[window.padding]
x = 3
y = 3
