[window.padding]
x = 3
y = 3

[font]
size = 11.0

[font.normal]
family = "RobotoMono Nerd Font"

[colors.primary]
background = "#222222"
foreground = "#F5EEE6"

[colors.normal]
black   = "#222222"
red     = "#545454"
green   = "#767676"
yellow  = "#CCCCCC"
blue    = "#999999"
magenta = "#E5E5E5"
cyan    = "#999999"
white   = "#F5EEE6"
